### ISSUE TITLE
Simple CG example

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/mosdef-workflows#9]
I'm thinking like an alkane based off of a 3:1 beads

@ahy3nz ?

**Comment by ahy3nz** [comment]
It's hard to design a helpful workflow because everyone does coarse-graining differently and has their own libraries to do so. I don't know anyone who actually uses the mbuild coarse graining functionality. I made #7 custom element issue because it assumes you've already done your own mapping (in whatever way you desire), but how to use the rest of the mosdef pipeline to parametrize a system
